meta_product_name: "Travel Colour"
meta_title: "Travel Colour - Find out which European countries are accepting UK tourists"
meta_description: "Find out which European countries are accepting UK tourists"
#meta_image: "cover.png" # should exist in `app/assets/images/`
